// Auto-generated by add_indices.py
import DocRemoteMetadataView from "./DocRemoteMetadataView";
import DocView from "./DocView";
import SearchView from "./SearchView";

export { DocRemoteMetadataView, DocView, SearchView };
