// Auto-generated by add_indices.py
import DocListView from "./DocListView";
import DocView from "./DocView";
import SearchBox from "./SearchBox";
import SearchBoxInfo from "./SearchBoxInfo";

export { DocListView, DocView, SearchBox, SearchBoxInfo };
