// Auto-generated by javascript_version.py
export const DATETIME_STR = "2025-08-03 09:37:42";
export const VERSION_DATETIME = new Date(DATETIME_STR);

const VERSION = { DATETIME_STR, VERSION_DATETIME };
export default VERSION;
