// Auto-generated by add_indices.py
import DocListView from "./DocListView";
import LangSourcesView from "./LangSourcesView";
import SearchBox from "./SearchBox";

export { DocListView, LangSourcesView, SearchBox };
