// Auto-generated by add_indices.py
import DocMetadataView from "./DocMetadataView";
import ReturnToSearchButton from "./ReturnToSearchButton";
import SearchBoxInfo from "./SearchBoxInfo";
import VersionView from "./VersionView";

export { DocMetadataView, ReturnToSearchButton, SearchBoxInfo, VersionView };
