// Auto-generated by add_indices.py
import DocMetadataView from "./DocMetadataView";
import SearchBoxInfo from "./SearchBoxInfo";
import VersionView from "./VersionView";

export { DocMetadataView, SearchBoxInfo, VersionView };
